const CFL_SAP_LOAD_PROCESS = "CFL_SAP_ON_DEMAND";

const JOB_STATUS = {
  QUEUED: "QUEUED",
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  PARTIAL_SUCCESS: "PARTIAL_SUCCESS",
  FAILED: "FAILED",
};

const JOB_TYPE = {
  VBELN: "VBELN",
  DATE_RANGE: "DATE_RANGE",
};

module.exports = {
  CFL_SAP_LOAD_PROCESS,
  JOB_STATUS,
  JOB_TYPE,
};
