const CFL_ROMANA_LOAD_PROCESS = "CFL_ROMANA_ON_DEMAND";

const JOB_STATUS = {
  QUEUED: "QUEUED",
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  PARTIAL_SUCCESS: "PARTIAL_SUCCESS",
  FAILED: "FAILED",
};

const JOB_TYPE = {
  DATE_RANGE: "DATE_RANGE",
  NPARTIDA: "NPARTIDA",
};

module.exports = {
  CFL_ROMANA_LOAD_PROCESS,
  JOB_STATUS,
  JOB_TYPE,
};
